cc_test(
    name = "test_chained_init",
    srcs = ["test_chained_init.cpp"],
    deps = ["//ciabatta"],
)

cc_test(
    name = "example",
    srcs = ["example.cpp"],
    copts = ["-fconcepts"],
    deps = ["//ciabatta"],
)
