cc_test(
    name = "test_chained_init",
    srcs = ["test_chained_init.cpp"],
    deps = ["//:ciabatta"],
)

cc_test(
    name = "example",
    srcs = ["example.cpp"],
    deps = ["//:ciabatta"],
)

cc_test(
    name = "test_provides",
    srcs = ["test_provides.cpp"],
    deps = ["//:ciabatta"],
)
